### ISSUE TITLE
Will there be a Fabric Floodgate?

### ISSUE THREAD

**Issue by QPCrummer** [GeyserMC/Geyser-Fabric#1]
I know that you just started this and I am so happy. I just don’t see the point if floodgate doesn’t get updated. I could already play geyser on fabric with bukkit4fabric. Not trying to rush you, just curious.

**Comment by DoctorMacc** [comment]
Hello! We do have an issue open for Fabric Floodgate support - now that I have experience with the Fabric platform, getting a Floodgate version will be easier in the future! Stay tuned.

**Comment by QPCrummer** [comment]
Thanks for getting back so quickly! I so glad to hear this. Hope it is a huge success!
