### ISSUE TITLE
Floodgate stopping the server from stopping properly.

### ISSUE THREAD

**Issue by AllThingsBroken** [GeyserMC/Geyser-Fabric#11]
After typing "stop" in the server console the server stops as usual until it gets to where it auto-closes and then it just hangs forever. Other mods (besides fabric API) are not needed to get this error. Here is my log:https://mclo.gs/2aQexS1.

**Comment by angrynerd** [comment]
Can confirm this happens with just geyser fabric floodgate not necessary. It is kinda annoying but not a deal breaker.

**Comment by Konicai** [comment]
Closing in favour of https://github.com/GeyserMC/Floodgate-Fabric/issues/25
