### ISSUE TITLE
Carpet Bots don’t Spawn

### ISSUE THREAD

**Issue by jkcoxson** [GeyserMC/Geyser-Fabric#13]
Using the latest version built on Jenkins, trying to spawn a bot using the carpet mod gives “Unexpected Error.” There is nothing in the logs or stdout, but bots do not spawn. 
Server Version: 1.16.5
Fabric Version: 0.7.3
Fabric API Version: 0.30.0
Carpet Version: 1.4.23
Tell me if there’s anything else you need!

**Comment by Camotoy** [comment]
I'm unable to replicate this with Floodgate 1.0 Geyser-Fabric.

**Comment by jkcoxson** [comment]
I forgot to mention, I am using Floodgate as well. Could you share your carpet configuration?

**Comment by Camotoy** [comment]
I don't see any Carpet config file, so whatever the defaults are. I can re-test with 2.0.

**Comment by Camotoy** [comment]
Can confirm with 2.0 and Floodgate.

**Comment by Camotoy** [comment]
This is a Floodgate issue, for reference.

**Comment by Camotoy** [comment]
Should be fixed with 84ddb0e.
