### ISSUE TITLE
Seems to not be on the latest version of bedrock

### ISSUE THREAD

**Issue by AlsoNiko** [GeyserMC/Geyser-Fabric#14]
It looks like this version of geyser doesn't work with the latest bedrock update, it has similar issues to when mainline geyser doesn't (Namely auto saying it is down and being unable to connect)

**Comment by Camotoy** [comment]
Those errors are not necessarily indicative of a non-updated Geyser. The builds should be up to date, and you should join our Discord server for more help as this is most likely a configuration or networking issue.

**Comment by AlsoNiko** [comment]
This was an issue with my port forward it seems, got it solved
