### ISSUE TITLE
Bedrock players cannot see or build anything above the bedrock ceiling

### ISSUE THREAD

**Issue by GoodPro712** [GeyserMC/Geyser-Fabric#15]
### **Description**
As of updating to fabric online mode floodgate, bedrock players now cannot build or see anything besides entities or particles above y=128 in the nether.

### **How to Reproduce**
Connect to the server while on bedrock
Teleport above the nether roof
Try to build or get another account that's on java to built or "float"

### **Files**

Screen recording of my friend who plays on bedrock:

https://user-images.githubusercontent.com/45357714/121134656-ffe7a780-c876-11eb-97f9-3c295a777415.mov

**Comment by CarrotsBunny** [comment]
this happens to me too

**Comment by Jens-Co** [comment]
There is an option in the geyser config file to enable nether roof building. "above-bedrock-nether-building"

**Comment by GoodPro712** [comment]
Thank you!

**Comment by EasyClifton** [comment]
It seems that you don't have the `above-nether-bedrock-building` option enabled in the Geyser config. Could you please check?

**Comment by GoodPro712** [comment]
It was enabled, but the server hadn't restarted so its fixed now, thank you for the lightning fast responses!
