### ISSUE TITLE
Lily pads can't be placed on bedrock

### ISSUE THREAD

**Issue by LUKEiAMurSISTER** [GeyserMC/Geyser-Fabric#17]
When placing a lily pad on water of 2+ blocks of height, it disappears from the world and inventory. Reappears in invetory on relog. 

Geyser-Fabric-1.4.0-SNAPSHOT.jar

21.06 08:37:32 [Server] Server thread/WARN Mismatch in destroy block pos: class_2338{x=0, y=0, z=0} class_2338{x=-366, y=78, z=-160}
21.06 08:37:35 [Server] Server thread/WARN Mismatch in destroy block pos: class_2338{x=0, y=0, z=0} class_2338{x=-365, y=78, z=-159}
21.06 08:37:39 [Server] Server thread/WARN Mismatch in destroy block pos: class_2338{x=0, y=0, z=0} class_2338{x=-365, y=78, z=-159}

**Comment by Camotoy** [comment]
As this would be a Geyser error, please reopen it on the main GitHub repository. Thank you!
