### ISSUE TITLE
Outdated on 1.17.1 server

### ISSUE THREAD

**Issue by Neubulae** [GeyserMC/Geyser-Fabric#19]

**Comment by rtm516** [comment]
Please provide a dump and a screenshot of the exact error.
`/geyser dump` in the server console then share the link here.

**Comment by Neubulae** [comment]
![4W)D(H@D46H5H I}FM{V3D3](https://user-images.githubusercontent.com/24774842/124772713-d8b3f100-df6e-11eb-92b5-16c5080d747e.jpg)

**Comment by Konicai** [comment]
Betas aren't supported. Geyser currently supports Minecraft Bedrock 1.17 - 1.17.2

**Comment by Camotoy** [comment]
That's your issue. Thanks anyway!
