### ISSUE TITLE
Can't successfully compile with Java 11

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/Geyser-Fabric#2]
Compiling with Java 11 prevents Geyser-Fabric from loading. *Will provide a stack trace later, just noting this down*

**Comment by DoctorMacc** [comment]
Reported in JellySquid's Discord: `Caused by: javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found` compiled with Java 8.

**Comment by Camotoy** [comment]
This is definitely not an issue anymore, heheh.
