### ISSUE TITLE
The relocation seemlingly causes the mod to cease to function

### ISSUE THREAD

**Issue by Neubulae** [GeyserMC/Geyser-Fabric#23]
[latest.log](https://github.com/GeyserMC/Geyser-Fabric/files/6831317/latest.log)
I'm using #23 on Jenkins.

**Comment by Neubulae** [comment]
https://github.com/GeyserMC/Geyser-Fabric/issues/22
I suppose this is the same problem as mine?

**Comment by Neubulae** [comment]
https://paste.gg/p/anonymous/5e3d0fc56edc4eb8be07bc747219ed50
with latest build

**Comment by Konicai** [comment]
duplicate of #22
