### ISSUE TITLE
Porblem

### ISSUE THREAD

**Issue by whes1015** [GeyserMC/Geyser-Fabric#36]
I have a question. When the setting is turned on, the screen is easy to freeze, and the chat room and the player move smoothly. What is causing this?

**Comment by Jens-Co** [comment]
Hello there, Would you mind elaborate a bit more ? 

* Which setting do you mean?
* what exactly are you doing that causes screen to freeze?
* what do you mean with chatroom and player moving "smooth" ?

Thanks!

**Comment by whes1015** [comment]
The server is paused, I just want to adjust my display area, but after pressing pause, the screen keeps stopping at the loading icon

**Comment by whes1015** [comment]
![2021-11-05_174015](https://user-images.githubusercontent.com/44525760/140612087-22ac6e57-8c84-4141-8591-c8132cf1a5cc.jpg)

**Comment by whes1015** [comment]
TPS 20 MSPT 10 Ping 10

**Comment by Jens-Co** [comment]
That doesn't look like a geyser related issue but rather an client problem. Anyway, can you provide us server logs ? You can upload logs with this website (https://mclo.gs) and include a geyser dump with it ( console command: geyser dump ) and paste the link in the comment. Thanks

**Comment by Chew** [comment]
To my knowledge, this is commonly caused by a bad connection (whether server or client caused is unknown).
