### ISSUE TITLE
Unable to join world

### ISSUE THREAD

**Issue by backpack5689** [GeyserMC/Geyser-Fabric#38]
Hey everyone!

So I've gone through the setup of installing this to my mod folder and configuring the config.yml file, however for some reason it is still not allowing me to connect through a bedrock client to this server!

To ensure that this would work without the firewall, I used a VPN and the internal IP address to connect, and still no dice. Here is a dump file that geyser created. Any ideas?

https://dump.geysermc.org/CaaigeHVdnrKf2k7A11n29e60DL2F0iN

**Comment by Camotoy** [comment]
For connection issues like these we ask you join our Discord. If you're unable to join Discord, you can still comment here, we just won't keep it open as it is very very likely not an issue on our end. See also: https://github.com/GeyserMC/Geyser/wiki/Fixing-'Unable-to-Connect-to-World'

Thank you for reporting anyway!
