### ISSUE TITLE
Death UI

### ISSUE THREAD

**Issue by whes1015** [GeyserMC/Geyser-Fabric#39]
When the player dies, he will receive two death screens

**Comment by Camotoy** [comment]
Bug reports like these likely affect the core Geyser module and not just Geyser-Fabric. I would appreciate if this issue were re-opened in the Geyser repository following the issue template. There's not much we can do with this amount of detail, unfortunately (I've died many times and haven't seem this behavior).
Thank you for reporting anyway!
