### ISSUE TITLE
Box UI

### ISSUE THREAD

**Issue by whes1015** [GeyserMC/Geyser-Fabric#40]
When the player stays away from the box due to various reasons and does not close the box, it will cause all the screen UI to disappear

**Comment by Camotoy** [comment]
Bug reports like these likely affect the core Geyser module and not just Geyser-Fabric. I would appreciate if this issue were re-opened in the Geyser repository following the issue template. There's not much we can do with this amount of detail, unfortunately. (I'm also not sure what you mean, so maybe provide a video if you can?)
Thank you for reporting anyway!
