### ISSUE TITLE
Death on rebirth

### ISSUE THREAD

**Issue by whes1015** [GeyserMC/Geyser-Fabric#41]
The player can receive damage when loading the world for the first time, or when respawning, which results in repeated deaths

**Comment by Camotoy** [comment]
Bug reports like these likely affect the core Geyser module and not just Geyser-Fabric. I would appreciate if this issue were re-opened in the Geyser repository following the issue template. There's not much we can do with this amount of detail, unfortunately.
Thank you for reporting anyway!
