### ISSUE TITLE
1.18 branch isn't on the OpenCollab maven

### ISSUE THREAD

**Issue by Oliver-makes-code** [GeyserMC/Geyser-Fabric#44]
On [the OpenCollab maven](https://repo.opencollab.dev/maven-snapshots/) there's Geyser-Fabric for 1.16 and 1.17, but not 1.18, and because of that, I can't include it in my Gradle project.

**Comment by Konicai** [comment]
If anyone is going to suggest using jitpack temporarily:
1. Geyser builds with Java 16
2. Geyser-Fabric uses gradle
3. Jitpack automatically uses Java 8 and doesn't detect the java version of gradle projects (unless specified in a separate jitpack.yml)

**Comment by Camotoy** [comment]
This should be resolved.
