### ISSUE TITLE
Failed to Sent packet

### ISSUE THREAD

**Issue by Vaneixus** [GeyserMC/Geyser-Fabric#45]
[crash-2021-12-15_17.38.14-client.txt](https://github.com/GeyserMC/Geyser-Fabric/files/7723179/crash-2021-12-15_17.38.14-client.txt)
Java client drops on connection throwing the error in the crash report while the server throws a Connection Reset Exception.  Got 30 mods, tested without them as well(only Fabric API, Geyser-Fabric 2.0.0 Snapshot and Floodgate Fabric were used.) Started crashing after loading an old 1.18 world. Server runs on 1.18.

**Comment by Camotoy** [comment]
I'm looking at the stack trace and this doesn't look like us. `method_26225` is `BlockStateBase::canOcclude` and `method_20479` is `LayerLightEngine::getStateAndOpacity`.

**Comment by Vaneixus** [comment]
well, that is the error thrown clientside, serverside, I am still trying to get the report, which included geyser and a thrown connection reset exception

**Comment by Vaneixus** [comment]
[crashreport.txt](https://github.com/GeyserMC/Geyser-Fabric/files/7728911/crashreport.txt)
here's the error from the server that leads to disconnection

**Comment by Konicai** [comment]
Please create a new bug report if you experience this on 1.19.2
