### ISSUE TITLE
[Bug] Linked accounts don't show your skin when on Bedrock

### ISSUE THREAD

**Issue by Oliver-makes-code** [GeyserMC/Geyser-Fabric#48]
If you have your account linked, and join from bedrock, your skin doesn't show up

**Comment by Konicai** [comment]
I believe this was fixed in https://github.com/GeyserMC/Floodgate-Fabric/commit/d52b33588ab367cc04c44356a651021ad9f538ef. Open a new issue on the Floodgate-Fabric repo if you still experience this.
