### ISSUE TITLE
ViaVersion doesn't seem to be detected

### ISSUE THREAD

**Issue by Zao-chen** [GeyserMC/Geyser-Fabric#49]
**Vision：**
Geyser-Fabric-1.4.3-SNAPSHOT
ViaVersion-4.2.2-SNAPSHOT
fabric-server-mc.1.17.1-loader.0.13.3-launcher.0.10.2
Bedrock1.18.30
**details**
ViaVersion successfully loaded on the server
Geyser also seems to be loaded successfully
1.18.2 java version players can also enter the server
But Bedrock Edition show
`Outdated Geyser proxy server! This server supports the following Bedrock Edition versions: 1.17.10/1.17.11, 1.17.30, 1.17.40`

**Comment by rtm516** [comment]
Your running an old version of geyser-fabric, please update it to join on newer bedrock versions.
https://ci.opencollab.dev/job/GeyserMC/job/Geyser-Fabric/job/java-1.18/

**Comment by Zao-chen** [comment]
> Your running an old version of geyser-fabric, please update it to join on newer bedrock versions. https://ci.opencollab.dev/job/GeyserMC/job/Geyser-Fabric/job/java-1.18/

My server is 1.17.1,https://ci.opencollab.dev/job/GeyserMC/job/Geyser-Fabric/job/java-1.18 isn't work.
and I want to let Bedrock Edition to join it.
I use Viafabric to allow the high version to join,and it work will.Java 1.18.2 can join it.but Bedrock Edition can't join
