### ISSUE TITLE
1.19 commit/build is on the 1.18 branch

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [GeyserMC/Geyser-Fabric#54]
The latest commit that updated this to 1.19 is on the 1.18 branch, which may be misleading because the build shows up as on the 1.18 branch on Jenkins too.

**Comment by Skywalker8510** [comment]
i cant find the 1.18 branch at all

**Comment by Kas-tle** [comment]
It was renamed to master so this can probably be closed now.
