### ISSUE TITLE
help for crossplay server setup using geyser + floodgate (1.18.2)

### ISSUE THREAD

**Issue by Rajbir98** [GeyserMC/Geyser-Fabric#57]
if you guys don't mind could you provide the downloads as I tried downloading many version but my server crashes.

**Comment by NatickYT** [comment]
What Software Are You Using For Your Server?

**Comment by NatickYT** [comment]
> What Software Are You Using For Your Server?

Oh Just Realised It Is Fabric

Use geysermc.org

**Comment by Konicai** [comment]
If you have an issue with the latest build of Geyser-Fabric that isn't yet posted on the Geyser or Geyser-Fabric Github repository, you can create a new bug report
