### ISSUE TITLE
1.19.10 Bedrock

### ISSUE THREAD

**Issue by firenh** [GeyserMC/Geyser-Fabric#59]
This version of Geyser is only working for Bedrock 1.19, not Bedrock 1.19.10, the latest version. I believe all that needs done is updating Geyser core from 2.0.4-SNAPSHOT to 2.0.5-SNAPSHOT, but on my device it kept on failing to build citing 'Failed to remap mods' even when I tried compiling without changing anything

**Comment by firenh** [comment]
Also if you all are busy I can try to do it, i just need to figure out how to get gradle to work

**Comment by Konicai** [comment]
Geyser-Fabric targets `2.1.0-SNAPSHOT` now
