### ISSUE TITLE
Outdated client error when using java edition 1.16.4

### ISSUE THREAD

**Issue by yitzy299** [GeyserMC/Geyser-Fabric#6]
I have a custom build of geyser fabric for Minecraft 1.16.4. The server runs fine, however this happens when a player tries to join from bedrock. I am pretty sure this is an issue with java 1.16.4. Do I need to wait for the next bedrock updates or is there another way to fix?
![B9431D62-5C97-4796-AB70-52EA57AEF6DC](https://user-images.githubusercontent.com/66269211/98441439-36e5b700-20f6-11eb-8e82-d896e05085c8.png)

**Comment by Ryorama** [comment]
I think you need to have the server on 1.16.3 as of now. Try that and see if it works, if not we will look for a fix.

**Comment by DoctorMacc** [comment]
> custom build
Do you have the latest Geyser dependency from Gradle?

**Comment by yitzy299** [comment]
> > custom build
> 
> Do you have the latest Geyser dependency from Gradle?

I am trying a new version now, will feedback when I have tested

**Comment by DoctorMacc** [comment]
This is now fixed.

**Comment by yitzy299** [comment]
Thanks! Is there a build ready?

**Comment by DoctorMacc** [comment]
Yes, there has been.
