### ISSUE TITLE
[Question] Bedrock users can't see the nether roof and I don't have access to the Geyser config file

### ISSUE THREAD

**Issue by 42Willow** [GeyserMC/Geyser-Fabric#63]
I am aware there is an option in the Geyser config file to trick bedrock clients into being able to view the Nether roof. Since I am using Minehut, I don't have access to the Geyser config file. But I do have access to the world files, is there any way for me to manually fix it or will that break it for Java users? (I have both Java and Bedrock players on my server.)

**Comment by Camotoy** [comment]
There isn't another workaround for this, unless there's some plugin that makes the Nether dimension point to the End's dimension - you'd have to ask Minehut to enable the setting.
