### ISSUE TITLE
Bedrock players cannot open chests and break blocks and their movement isnt registered in java clients

### ISSUE THREAD

**Issue by Kavin7000** [GeyserMC/Geyser-Fabric#64]
I use Geyser-Fabric on my server and i am experiencing an error on the bedrock side. Whenever a bedrock client moves or tries to break blocks, I get this error
![image](https://user-images.githubusercontent.com/78969134/183820659-aaaa0885-5e3c-4b5d-8aad-6e1d46340f83.png)
And the bedrock client doesnt move in the view of a java player. Bedrock players cant take damage, open chests and break blocks
More proof shall be sent if required

**Comment by Kavin7000** [comment]
I also have this video from which you can clearly see that my internet is not the problem as I can kill mobs with my Java client but cant break blocks with my Bedrock client. When I try to break blocks with the Bedrock client, the blocks just disappear and I get that error in the console
https://user-images.githubusercontent.com/78969134/183822677-421ade4a-7bab-40b2-bf66-a1d237301092.mp4

**Comment by Konicai** [comment]
Read https://github.com/GeyserMC/Geyser/issues/2861

**Comment by Konicai** [comment]
If you still experience this issue after reviewing the workarounds in the link above, please let us know.
