### ISSUE TITLE
Server crashes with new 1.19.30 update

### ISSUE THREAD

**Issue by N0tJust1n** [GeyserMC/Geyser-Fabric#68]
https://pastebin.com/M9DYDdxa

I get this error with the new jar that was just built with Jenkins here recently. Thanks for all your hard work!

**Comment by mangosurvival** [comment]
it also crashes for me, but it says something about datapacks. i dont have any datapack, only fabric api, minimotd and the latest geyser build.

https://pastebin.com/AvMt16DT

**Comment by gamer50082** [comment]
Pls don’t use pastebin

**Comment by mangosurvival** [comment]
sorry about that, where do you prefer to see the log?

**Comment by Konicai** [comment]
@mangosurvival Pastebin is absolutely fine (mclogs is good at sensoring private info tough). Your issue isn't related to this issue report though, you can create your own if you want. Please include the same information that an issue report on https://github.com/GeyserMC/Geyser asks for.

**Comment by gamer50082** [comment]
> sorry about that, where do you prefer to see the log?

https://mclo.gs/

**Comment by N0tJust1n** [comment]
Just randomly stopped happening with no configuration changes or updates? Closing for now unless someone can produce the same issue.
