### ISSUE TITLE
Optifine/Optifabric not loading with Geyser-Fabric (Client-Side)

### ISSUE THREAD

**Issue by HelveticaToast** [GeyserMC/Geyser-Fabric#7]
When attempting to load Optifine/Optifabric with Geyser-Fabric, I get the following error.
https://hasteb.in/epakoqop
The game loads fine, but Optifabric does not load. Without Geyser-Fabric, Optifabric loads perfectly fine.

Minecraft Version: 1.16.3
Fabric Version: 0.10.7
FabricAPI Version: 0.25.0+build.415-1.16
Geyser-Fabric Version: #18

Other Mods:
modmenu-1.14.6+build.31
okzoomer-4.0.1+1.16.2
phosphor-fabric-mc1.16.1-0.6.0+build.7
RoughlyEnoughItems-5.6.2

I'll try again without the other mods, and give an update on what happens.

**Comment by HelveticaToast** [comment]
Can Confirm, same issue without the other mods

**Comment by Camotoy** [comment]
This has probably been fixed by our ASM relocation.
