### ISSUE TITLE
Geyser not loading even with floodgate (QUILT)

### ISSUE THREAD

**Issue by ZephemusX** [GeyserMC/Geyser-Fabric#73]
The last geyser version that doesn't load without floodgate even with floodgate don't work with quilt, I don't know if you are interested in fixing quilt compatibility, but just letting you know.

It seems the problem is floodgate.
https://mclo.gs/cN67eEY

**Comment by Konicai** [comment]
Please view this issue: https://github.com/GeyserMC/Floodgate-Fabric/issues/7

If your error still persists after following the instructions there, please contact us on our Discord: http://discord.geysermc.org/
